ChapeauApp/Controllers/BarKitchenController.cs
using ChapeauApp.Models.ViewModels;
using ChapeauApp.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace ChapeauApp.Controllers
{
    public class BarKitchenController : Controller
    {
        private readonly IOrdersService _ordersService;
        public BarKitchenController(IOrdersService ordersService)
        {
            _ordersService = ordersService;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult RunningOrders(string section) 
        {
            List<RunningOrdersViewModel> runningOrders = _ordersService.GetRunningOrdersBySection(section);
            return View(runningOrders);
        }
    }
}

ChapeauApp/Controllers/MenuController.cs
using ChapeauApp.Enums;
using ChapeauApp.Models;
using ChapeauApp.Models.ViewModels;
using ChapeauApp.Repositories.Interfaces;
using ChapeauApp.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace ChapeauApp.Controllers
{
    public class MenuController : Controller
    {
        private readonly IMenusService _menusService;
        public MenuController(IMenusService menusService)
        {
            _menusService = menusService;
        }
        
        //cardName is menuName in the database.
        //itemCategory is itemType in the database but should have been courseName to avoid confusion.
        //Naming things really is some of the most difficult things in programming.
        public IActionResult Index(string? card, string? category)
        {
            try
            {
                //Hardcoded offline backup (outdated)
                /*MenuItemCard card1 = MenuItemCard.Lunch;
                MenuItemCard card2 = MenuItemCard.Diner;
                MenuItemCard card3 = MenuItemCard.Dranken;
                List<MenuItem> AllMenuItems = [
                    new(1, card3, "Coffee", (decimal)2.99, "Drink", "This is coffee", 12, 9),
                    new(2, card3, "Cola", (decimal)1.99, "Drink", "This is cola", 19, 9),
                    new(3, card1, "Chips", (decimal)2.99, "Drink", "This is chips", 0, 9),
                    new(4, card3, "Wine", (decimal)5.99, "Drink", "This is wine", 2, 21)];
                Menu menu = new(AllMenuItems);
                MenuViewModel menuViewModel = new (menu);*/
                MenuViewModel menuViewModel = _menusService.GetMenuViewModel(card, category);
                return View(menuViewModel);
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = $"The menu could not be loaded: {ex.Message}";//This message should be updated to give the client a clear idea of what went wrong.
                return RedirectToAction("Index", "Home");
            }
        }
    }
}

ChapeauApp/Controllers/OrdersController.cs
using ChapeauApp.Models;
using ChapeauApp.Models.ViewModels;
using ChapeauApp.Repositories.Interfaces;
using Microsoft.AspNetCore.Mvc;
using ChapeauApp.Services.Interfaces;
using ChapeauApp.Services;

namespace ChapeauApp.Controllers
{
    public class OrdersController : Controller
    {
        private readonly IOrdersService _ordersService;
        private readonly ITableService _tableService;
        private readonly IVatsService _vatsService;
        
        public OrdersController(IOrdersService ordersService, ITableService tableService, IVatsService vatsService)
        {
            _ordersService = ordersService;
            _tableService = tableService;            
            _vatsService = vatsService;
        }

        /*public IActionResult Index()
        {
            //List<Table> tables = _tablesRepository.GetAllTables();
            List<TableViewModel> tables = _tableService.GetAllTables();

            //orderviewmodel
            OrdersViewModel ordersViewModel = new OrdersViewModel
            {
                Tables = tables
            };

            return View(ordersViewModel);
        }*/

        // shows ordered items (orders)
        public IActionResult GetOrderByTableNumber(int tableNumber)
        {
            Order order = _ordersService.GetOrderByTableNumber(tableNumber);

            if (order == null)
            {
                return NotFound($"No order found for table: {tableNumber}");
            }

            return View(order);
            // calling the methode GetOrderByBillId(int bllId)
            //return GetOrderByBillId(order.Bill.BillId);
        }

        public IActionResult GetOrderByBillId(int billId)
        {
            Order order = _ordersService.GetOrderByBillId(billId);

            if (order == null)
            {
                return NotFound("Order not found for this bill.");
            }

            //orderServices to calculate totalpriceamount
            decimal totalPriceAmount = _ordersService.CalculateTotalPriceAmount(order.OrderItems);

            //vatservice to display low and high vat amount
            VatSummary vatTotals = _vatsService.CalculateVatTotalAmount(order.OrderItems);

            //orderviewmodel
            OrdersViewModel ordersViewModel = new OrdersViewModel
            {
                //Table = order.Table,
                Order = order,
                TotalPriceAmount = totalPriceAmount,
                VatTotals = vatTotals
            };

            return View(ordersViewModel);
        }
    }
}

ChapeauApp/Controllers/TablesController.cs
using ChapeauApp.Services.Interfaces;
using ChapeauApp.Enums;
using Microsoft.AspNetCore.Mvc;
using ChapeauApp.Models.ViewModels;

namespace ChapeauApp.Controllers
{
   
    public class TablesController : Controller
    {
        private readonly ITableService _tableService;

        public TablesController(ITableService tableService)
        {
            _tableService = tableService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            try
            {
                TablesViewModel tablesViewModels = _tableService.GetAllTables();
                ViewData["place"] = "TableIndex";
                return View(tablesViewModels);
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = $"The tables could not be loaded: {ex.Message}.";
                return RedirectToAction("Index", "Home");
            }
        }
        [HttpGet]
        public IActionResult Table(int tableNumber)
        {
            try
            {
                TableViewModel tableViewModel = _tableService.GetTableById(tableNumber);
                return View(tableViewModel);
            }
            catch(Exception ex)
            {
                TempData["ErrorMessage"] = $"Something went wrong: {ex.Message}.";//This message should be updated to give the client a clear idea of what went wrong.
                return RedirectToAction("Index", "Table");
            }
        }

        [HttpGet]
        public IActionResult Update(TableViewModel tableViewModel) 
        {
            try
            {
                ViewData["OldStatus"] = tableViewModel.TableStatus;
                return View(tableViewModel);
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = $"Something went wrong: {ex.Message}.";//This message should be updated to give the client a clear idea of what went wrong.
                return RedirectToAction("Index", "Table");
            }
        }
        [HttpPost]
        public IActionResult Update(TableUpdateViewModel tableUpdateViewModel)
        {
            try
            {
                _tableService.UpdateTableStatus(tableUpdateViewModel);
                TempData["Message"] = "TableStatus was succesfully updated.";
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = $"Something went wrong: {ex.Message}.";//This message should be updated to give the client a clear idea of what went wrong.
                return RedirectToAction("Index", "Table");
            }
        }
    }
}

ChapeauApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ChapeauApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ChapeauApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ChapeauApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Menu" asp-action="Index">Menu</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Orders" asp-action="Index">Orders</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="OrderItems" asp-action="Index">OrderItems</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tables" asp-action="Index">Tables</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="BarKitchen" asp-action="Index">Bar/Kitchen</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - ChapeauApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>